# Port.io SonarQube Integration Mapping Configuration
# Paste this into the "Edit Configuration" YAML editor of your SonarQube Integration in Port.io.

resources:
  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: "\"pwa-client-app\"" # Target our microservice ID
          blueprint: "microservice"
          properties:
            qualityGate: ".qualityGate.status" # e.g. OK, ERROR
            bugs: ".measures.bugs // 0"
            vulnerabilities: ".measures.vulnerabilities // 0"
            coverage: ".measures.coverage // 100"
